# Generated by Django 5.0.4 on 2024-04-09 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0001_initial'),
        ('meal_app', '0006_remove_meal_food_remove_meal_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food', to='meal_app.meal'),
        ),
    ]
