# Generated by Django 5.0.4 on 2024-04-09 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0004_alter_meal_meal_date_time_alter_meal_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='food_id',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='review_id',
            new_name='review',
        ),
    ]
