# Generated by Django 5.0.4 on 2024-04-11 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0006_remove_meal_food_remove_meal_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
