# Generated by Django 5.0.4 on 2024-04-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0008_alter_meal_meal_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
